"""initial schema

Revision ID: b86554c1b399
Revises: 
Create Date: 2026-04-23 17:37:15.547858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b86554c1b399'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'completed', 'failed', 'aborted', name='sessionstatus', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('yolo', 'hitl', name='sessionmode', native_enum=False, length=16), nullable=False),
    sa.Column('working_directory', sa.Text(), nullable=False),
    sa.Column('raw_input', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'active', 'completed', 'revised', name='planstatus', native_enum=False, length=32), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'revision', name='uq_session_revision')
    )
    op.create_index(op.f('ix_execution_plans_session_id'), 'execution_plans', ['session_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('foundational', 'implementation', 'validation', 'integration', name='tasktype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', name='taskstatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('parallel_group', sa.String(length=255), nullable=True),
    sa.Column('checkpoint_before', sa.Boolean(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['execution_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_plan_id'), 'tasks', ['plan_id'], unique=False)
    op.create_index(op.f('ix_tasks_session_id'), 'tasks', ['session_id'], unique=False)
    op.create_table('agent_assignments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_type', sa.Enum('lead', 'coding', 'testing', 'requirements', 'integration', 'other', name='agenttype', native_enum=False, length=32), nullable=False),
    sa.Column('provider', sa.Enum('gemini', 'anthropic', 'openai', name='provider', native_enum=False, length=32), nullable=False),
    sa.Column('mode', sa.Enum('adapter', 'api', name='agentmode', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'running', 'completed', 'failed', name='assignmentstatus', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_assignments_session_id'), 'agent_assignments', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_assignments_task_id'), 'agent_assignments', ['task_id'], unique=False)
    op.create_table('checkpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('plan_approval', 'pre_fanout', 'mid_execution', 'unexpected', name='checkpointtype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'revised', 'cancelled', name='checkpointstatus', native_enum=False, length=32), nullable=False),
    sa.Column('presented', sa.JSON(), nullable=False),
    sa.Column('response', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_checkpoints_session_id'), 'checkpoints', ['session_id'], unique=False)
    op.create_index(op.f('ix_checkpoints_task_id'), 'checkpoints', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('depends_on_task_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'depends_on_task_id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('operation', sa.Enum('created', 'updated', 'deleted', name='artifactoperation', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['agent_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_assignment_id'), 'artifacts', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_artifacts_session_id'), 'artifacts', ['session_id'], unique=False)
    op.create_index(op.f('ix_artifacts_task_id'), 'artifacts', ['task_id'], unique=False)
    op.create_table('task_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('time_to_first_token_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('tokens_total', sa.Integer(), nullable=True),
    sa.Column('tokens_estimated', sa.Boolean(), nullable=False),
    sa.Column('token_deviation', sa.String(length=32), nullable=True),
    sa.Column('artifacts_created', sa.Integer(), nullable=False),
    sa.Column('artifacts_updated', sa.Integer(), nullable=False),
    sa.Column('artifacts_deleted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['agent_assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assignment_id')
    )
    op.create_index(op.f('ix_task_metrics_session_id'), 'task_metrics', ['session_id'], unique=False)
    op.create_index(op.f('ix_task_metrics_task_id'), 'task_metrics', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_metrics_task_id'), table_name='task_metrics')
    op.drop_index(op.f('ix_task_metrics_session_id'), table_name='task_metrics')
    op.drop_table('task_metrics')
    op.drop_index(op.f('ix_artifacts_task_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_session_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_assignment_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_checkpoints_task_id'), table_name='checkpoints')
    op.drop_index(op.f('ix_checkpoints_session_id'), table_name='checkpoints')
    op.drop_table('checkpoints')
    op.drop_index(op.f('ix_agent_assignments_task_id'), table_name='agent_assignments')
    op.drop_index(op.f('ix_agent_assignments_session_id'), table_name='agent_assignments')
    op.drop_table('agent_assignments')
    op.drop_index(op.f('ix_tasks_session_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_plan_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_execution_plans_session_id'), table_name='execution_plans')
    op.drop_table('execution_plans')
    op.drop_table('sessions')
    # ### end Alembic commands ###
